### ISSUE TITLE
Cannot run in Binder: Need for memory optimisation in curve mode

### ISSUE THREAD

**Issue by lfnothias** [mohimanilab/MS2Planner#1]
The memory usage of the curve mode prevents running the code in a Binder server:
I observed that the following steps/loops are using a massive amount of memory (from 500 MB to 8 GB in 10 seconds):
https://github.com/mohimanilab/MS2Planner/blob/837f563f4e092683ad15c205687bb3dfa671125c/path_curve.py#L411

and also: 
https://github.com/mohimanilab/MS2Planner/blob/837f563f4e092683ad15c205687bb3dfa671125c/path_curve.py#L449

using the following arguments:
`python3 MS2Planner/path_finder.py curve input.csv output.csv 0 3 3 -infile_raw input.mzML -intensity_accu 1000000.0 -restriction 2 0.02 -isolation 1.5 -delay 0.02 -min_scan 0.1 -max_scan 0.5 -cluster kNN`

It can reproduced here with the input files from 1) Euphorbia dataset.
https://notebooks.gesis.org/binder/v2/gh/lfnothias/IODA_MassSpec/master?urlpath=lab/tree/home/jovyan/IODA_MS2Planner.ipynb

Any chance there is a small change that can resolve this ?

**Comment by zeyuanz** [comment]
Thanks for the comments. I developed the code on my PC which is 16 GB memory. I also noticed this problem during development, but I cannot find a easy way to reduce the memory usage further more. I think the best way to solve this is to request 16GB memory or more on the server if it is possible.

**Comment by lfnothias** [comment]
Thanks a lot. We will simply not provide Binder support for the curve mode until that is resolved.
